version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz2wsx
      MYSQL_DATABASE: petz
      MYSQL_USER: user_petz
      MYSQL_PASSWORD: r4cc00n
